server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arbarik/cloud-config-repo.git
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/arbarik/cloud-config-perf
              search-paths:
               - 'station*'
